find -name '1332_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 1332_*.png %.png
find -name '1333_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 1333_*.png %.png
find -name '1605_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 1605_*.png %.png
find -name '1721_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 1721_*.png %.png
find -name '1801_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 1801_*.png %.png
find -name '1802_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 1802_*.png %.png
find -name '1803_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 1803_*.png %.png
find -name '1808_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 1808_*.png %.png
find -name '1812_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 1812_*.png %.png
find -name '1925_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 1925_*.png %.png
find -name '1928_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 1928_*.png %.png
find -name '1963_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 1963_*.png %.png
find -name '2002_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 2002_*.png %.png
find -name '2269_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 2269_*.png %.png
find -name '2282_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 2282_*.png %.png
find -name '2413_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 2413_*.png %.png
find -name '2432_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 2432_*.png %.png
find -name '2501_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 2501_*.png %.png
find -name '2502_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 2502_*.png %.png
find -name '2503_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 2503_*.png %.png
find -name '2531_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 2531_*.png %.png
find -name '2768_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 2768_*.png %.png
find -name '2801_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 2801_*.png %.png
find -name '2802_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 2802_*.png %.png
find -name '2871_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 2871_*.png %.png
find -name '2914_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 2914_*.png %.png
find -name '3086_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 3086_*.png %.png
find -name '3099_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 3099_*.png %.png
find -name '3101_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 3101_*.png %.png
find -name '3103_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 3103_*.png %.png
find -name '3105_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 3105_*.png %.png
find -name '3289_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 3289_*.png %.png
find -name '3382_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 3382_*.png %.png
find -name '3401_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 3401_*.png %.png
find -name '3402_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 3402_*.png %.png
find -name '3405_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 3405_*.png %.png
find -name '3407_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 3407_*.png %.png
find -name '3436_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 3436_*.png %.png
find -name '3861_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 3861_*.png %.png
find -name '3863_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 3863_*.png %.png
find -name '4004_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4004_*.png %.png
find -name '4005_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4005_*.png %.png
find -name '4021_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4021_*.png %.png
find -name '4042_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4042_*.png %.png
find -name '4043_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4043_*.png %.png
find -name '4061_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4061_*.png %.png
find -name '4063_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4063_*.png %.png
find -name '4151_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4151_*.png %.png
find -name '4183_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4183_*.png %.png
find -name '4188_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4188_*.png %.png
find -name '4208_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4208_*.png %.png
find -name '4272_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4272_*.png %.png
find -name '4324_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4324_*.png %.png
find -name '4452_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4452_*.png %.png
find -name '4502_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4502_*.png %.png
find -name '4503_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4503_*.png %.png
find -name '4506_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4506_*.png %.png
find -name '4507_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4507_*.png %.png
find -name '4519_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4519_*.png %.png
find -name '4523_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4523_*.png %.png
find -name '4543_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4543_*.png %.png
find -name '4568_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4568_*.png %.png
find -name '4578_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4578_*.png %.png
find -name '4631_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4631_*.png %.png
find -name '4689_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4689_*.png %.png
find -name '4704_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4704_*.png %.png
find -name '4751_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4751_*.png %.png
find -name '4755_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4755_*.png %.png
find -name '4901_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4901_*.png %.png
find -name '4902_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4902_*.png %.png
find -name '4911_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 4911_*.png %.png
find -name '5019_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5019_*.png %.png
find -name '5020_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5020_*.png %.png
find -name '5101_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5101_*.png %.png
find -name '5108_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5108_*.png %.png
find -name '5201_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5201_*.png %.png
find -name '5202_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5202_*.png %.png
find -name '5214_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5214_*.png %.png
find -name '5232_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5232_*.png %.png
find -name '5233_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5233_*.png %.png
find -name '5301_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5301_*.png %.png
find -name '5332_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5332_*.png %.png
find -name '5333_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5333_*.png %.png
find -name '5401_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5401_*.png %.png
find -name '5406_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5406_*.png %.png
find -name '5411_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5411_*.png %.png
find -name '5541_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5541_*.png %.png
find -name '5631_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5631_*.png %.png
find -name '5703_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5703_*.png %.png
find -name '5706_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5706_*.png %.png
find -name '5707_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5707_*.png %.png
find -name '5711_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5711_*.png %.png
find -name '5713_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5713_*.png %.png
find -name '5714_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5714_*.png %.png
find -name '5801_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5801_*.png %.png
find -name '5802_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5802_*.png %.png
find -name '5803_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5803_*.png %.png
find -name '5901_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 5901_*.png %.png
find -name '6098_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6098_*.png %.png
find -name '6103_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6103_*.png %.png
find -name '6113_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6113_*.png %.png
find -name '6178_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6178_*.png %.png
find -name '6301_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6301_*.png %.png
find -name '6302_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6302_*.png %.png
find -name '6305_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6305_*.png %.png
find -name '6326_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6326_*.png %.png
find -name '6361_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6361_*.png %.png
find -name '6367_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6367_*.png %.png
find -name '6471_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6471_*.png %.png
find -name '6472_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6472_*.png %.png
find -name '6473_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6473_*.png %.png
find -name '6479_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6479_*.png %.png
find -name '6501_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6501_*.png %.png
find -name '6503_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6503_*.png %.png
find -name '6504_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6504_*.png %.png
find -name '6506_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6506_*.png %.png
find -name '6645_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6645_*.png %.png
find -name '6674_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6674_*.png %.png
find -name '6701_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6701_*.png %.png
find -name '6702_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6702_*.png %.png
find -name '6703_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6703_*.png %.png
find -name '6724_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6724_*.png %.png
find -name '6752_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6752_*.png %.png
find -name '6758_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6758_*.png %.png
find -name '6762_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6762_*.png %.png
find -name '6770_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6770_*.png %.png
find -name '6841_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6841_*.png %.png
find -name '6857_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6857_*.png %.png
find -name '6902_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6902_*.png %.png
find -name '6952_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6952_*.png %.png
find -name '6954_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6954_*.png %.png
find -name '6971_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6971_*.png %.png
find -name '6976_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6976_*.png %.png
find -name '6988_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 6988_*.png %.png
find -name '7003_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7003_*.png %.png
find -name '7004_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7004_*.png %.png
find -name '7011_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7011_*.png %.png
find -name '7012_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7012_*.png %.png
find -name '7013_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7013_*.png %.png
find -name '7186_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7186_*.png %.png
find -name '7201_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7201_*.png %.png
find -name '7202_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7202_*.png %.png
find -name '7203_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7203_*.png %.png
find -name '7205_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7205_*.png %.png
find -name '7211_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7211_*.png %.png
find -name '7261_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7261_*.png %.png
find -name '7267_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7267_*.png %.png
find -name '7269_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7269_*.png %.png
find -name '7270_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7270_*.png %.png
find -name '7272_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7272_*.png %.png
find -name '7731_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7731_*.png %.png
find -name '7733_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7733_*.png %.png
find -name '7735_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7735_*.png %.png
find -name '7751_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7751_*.png %.png
find -name '7752_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7752_*.png %.png
find -name '7762_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7762_*.png %.png
find -name '7832_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7832_*.png %.png
find -name '7911_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7911_*.png %.png
find -name '7912_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7912_*.png %.png
find -name '7951_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 7951_*.png %.png
find -name '8001_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8001_*.png %.png
find -name '8002_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8002_*.png %.png
find -name '8015_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8015_*.png %.png
find -name '8028_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8028_*.png %.png
find -name '8031_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8031_*.png %.png
find -name '8035_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8035_*.png %.png
find -name '8053_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8053_*.png %.png
find -name '8058_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8058_*.png %.png
find -name '8233_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8233_*.png %.png
find -name '8252_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8252_*.png %.png
find -name '8253_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8253_*.png %.png
find -name '8267_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8267_*.png %.png
find -name '8303_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8303_*.png %.png
find -name '8304_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8304_*.png %.png
find -name '8306_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8306_*.png %.png
find -name '8308_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8308_*.png %.png
find -name '8309_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8309_*.png %.png
find -name '8316_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8316_*.png %.png
find -name '8331_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8331_*.png %.png
find -name '8354_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8354_*.png %.png
find -name '8355_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8355_*.png %.png
find -name '8411_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8411_*.png %.png
find -name '8601_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8601_*.png %.png
find -name '8604_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8604_*.png %.png
find -name '8628_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8628_*.png %.png
find -name '8630_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8630_*.png %.png
find -name '8697_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8697_*.png %.png
find -name '8725_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8725_*.png %.png
find -name '8750_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8750_*.png %.png
find -name '8766_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8766_*.png %.png
find -name '8795_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8795_*.png %.png
find -name '8801_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8801_*.png %.png
find -name '8802_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8802_*.png %.png
find -name '8804_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8804_*.png %.png
find -name '8830_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 8830_*.png %.png
find -name '9001_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9001_*.png %.png
find -name '9005_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9005_*.png %.png
find -name '9007_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9007_*.png %.png
find -name '9008_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9008_*.png %.png
find -name '9009_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9009_*.png %.png
find -name '9020_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9020_*.png %.png
find -name '9021_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9021_*.png %.png
find -name '9022_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9022_*.png %.png
find -name '9062_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9062_*.png %.png
find -name '9064_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9064_*.png %.png
find -name '9101_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9101_*.png %.png
find -name '9104_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9104_*.png %.png
find -name '9107_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9107_*.png %.png
find -name '9202_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9202_*.png %.png
find -name '9301_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9301_*.png %.png
find -name '9412_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9412_*.png %.png
find -name '9432_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9432_*.png %.png
find -name '9433_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9433_*.png %.png
find -name '9437_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9437_*.png %.png
find -name '9501_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9501_*.png %.png
find -name '9502_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9502_*.png %.png
find -name '9503_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9503_*.png %.png
find -name '9531_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9531_*.png %.png
find -name '9532_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9532_*.png %.png
find -name '9602_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9602_*.png %.png
find -name '9613_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9613_*.png %.png
find -name '9735_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9735_*.png %.png
find -name '9766_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9766_*.png %.png
find -name '9983_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9983_*.png %.png
find -name '9984_*' -printf '%f\n' | sed -e 's/_.*$//g' | xargs -I % mv 9984_*.png %.png
